yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('group_posts/<slug:slug>/', views.group_posts, name='group_posts'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='users/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),    
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/about/models.py
from django.db import models

# Create your models here.

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(primary_key=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts', blank=True, null=True)

    def __str__(self):
        return self.text    

    class Meta:
        ordering = ['-pub_date']

yatube/users/models.py
from django.db import models

# Create your models here.

yatube/posts/forms.py
from django.forms import ModelForm
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
 

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email') 

yatube/about/views.py
from django.shortcuts import render

from django.views.generic.base import TemplateView

class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'

class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator

from .models import Group, Post, User
from posts.forms import PostForm


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context) 


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:settings.ITEMS_COUNT]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

def profile(request, username):
    posts = Post.objects.filter(author__username=username)
    user = User.objects.get(username=username)
    post_count = posts.count()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'post_count': post_count,
        'user': user
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = Post.objects.get(pk=post_id)
    posts = Post.objects.filter(author__id=post.author_id)
    post_count = posts.count()
    context = {
        'post': post,
        'post_count': post_count,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = User.objects.get(username=request.user.username)
            post.save()
            return redirect('/profile/' + request.user.username)

    form = PostForm(request.GET)
    posts_group = Group.objects.all()
    context = {
        'posts_group': posts_group,
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


def post_edit(request, post_id):
    post = Post.objects.get(pk=post_id)
    if post.author_id != request.user.id:
        return redirect('/posts/' + str(post_id))
    
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = User.objects.get(username=request.user.username)
            post.save()
            return

    form = PostForm(request.GET)
    posts_group = Group.objects.all()
    context = {
        'posts_group': posts_group,
        'form': form,
        'is_edit': True,
        'text': post.text,
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html' 

yatube/templates/about/author.html
{% extends "base.html" %}

{% block title %}Об авторе проекта{% endblock %}

{% block content %}
<main> 
  <div class="container py-5">
    <h1>Привет, я автор</h1>
    <p>Меня зовут Ирина. Целых 17 лет я работала переводчиком технической документации,
    но пришло время сменить сферу деятельности, т. к. "на пятки наступает" ИИ —
    теперь уже не нужно часами сидеть и ломать голову над тем, что же написали китайцы на английском,
    достаточно просто проверить текст, переведенный автоматическим переводчиком.</br>
    Программирование меня интересовало давно, но времени всерьез заняться изучением не было,
    и вот в свои 38 я решила, что пора. Бросила работу и пошла учиться!</br>
    Надеюсь на успех! Ведь у меня есть моя супер-муза — котенок Беладонна! :)))</p>
  </div>
  <div class="container">
    <img src="/static/img/cat.png" width="170" height="250">
  </div>  
</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <div style="text-indent:25px;"><h1>Технологии</h1></div>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>Данный проект создан на языке программирования Python с использованием фреймворка Django.</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <title>{% block title %}{% endblock %}</title>   
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main> 
      {% block content %}
      Контент в файлах
      {% endblock %} 
    </main>
    {% include 'includes/footer.html' %}    
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        {% load static %}
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube</a>
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
          href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
          href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:password_change' %}active{% endif %}"
          href="{% url 'users:password_change' %}">Изменить пароль</a> 
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}"
          href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}"
          href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}"
          href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>      
</header>

yatube/templates/includes/main.html
<ul>
  <li>
  Автор: {{ post.author.get_full_name }}
  </li>
  <li>
  Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>{{ post.text|linebreaksbr }}</p>

yatube/templates/posts/create_post.html
{% extends "base.html" %}

{% block title %}Новый пост{% endblock %}
{% block header %}Новый пост{% endblock %}
{% block content %}
{% load user_filters %}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}    
            Добавить запись
          {% endif %}        
        </div>
        <div class="card-body">       
          <form method="post" action="">
          {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_text">
                Текст поста                  
                <span class="required text-danger" >*</span>                  
              </label>
              <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                {{ text }}
              </textarea>                
              <small id="id_text-help" class="form-text text-muted">
                Текст нового поста
              </small>                  
            </div>            
            <div class="form-group row my-3 p-3">
              <label for="id_group">
                Группа                  
              </label>
              <select name="group" class="form-control" id="id_group">
                <option value="" selected>---------</option>
                {% for group in posts_group %}
                <option value="{{ group.slug }}">{{ group.title }}</option>
                {% endfor %}
              </select>
              <small id="id_group-help" class="form-text text-muted">
                Группа, к которой будет относиться пост
              </small>
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}  
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}Записи сообщества "{{ group }}" {% endblock %}

{% block content %}
<main>
  <div class="container py-5">
    <h1>{{ group }}</h1>
    <p>
    {{ group.description }}
    </p>
    <article>
    {% for post in posts %}
    {% include 'includes/main.html' %}
    {% endfor %}
    </article>
  </div>  
</main>
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}Последние обновления на сайте{% endblock %}

{% block content %} 
<main> 
  <div class="container py-5">     
    <h1>Последние обновления на сайте</h1>
    <article>
    {% for post in page_obj %}
    {% include 'includes/main.html' %}  
    {% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %} 
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </article>
  </div>
{% include 'posts/includes/paginator.html' %}
</main>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}

{% block title %}Пост: {{ post.text|truncatewords:30 }} {% endblock %}

{% block content %}

{% load user_filters %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %}   
      <li class="list-group-item">
        Группа: {{ post.group.title }}</br>
      <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
      {% endif %}
      </li>
      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора: {{ post_count }}      
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>{{ post.text }}</p>
  </article>
</div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}

{% block title %}Профайл пользователя {{ user.get_full_name }}{% endblock %}

{% block content %}

{% load user_filters %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{ user.get_full_name }} </h1>
      <h3>Всего постов: {{ post_count }} </h3>   
      <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{{ posts }}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li>
        </ul>
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
      </br>       
      <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>        
      <hr>
      {% endfor %}
      </article>
      {% include 'posts/includes/paginator.html' %}      
  </div>
{% endblock %}

yatube/templates/posts/update_post.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Редактировать пост</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">              
              <a class="nav-link" href="../about/author.html">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../about/tech.html">
                Технологии
              </a>
            </li>
            <!-- пункты меню видны только авторизованному пользователю -->
            <li class="nav-item">
              <a class="nav-link active" href="../posts/create_post.html">
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/password_change_form.html">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/logged_out.html">Выйти</a>
            </li>
            <li>
              Пользователь: leo
            <li>
            <!-- конец пункты меню видны только авторизованному пользователю -->
            <!-- пункты меню видны только неавторизованному пользователю -->
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/login.html">
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/signup.html">Регистрация</a>
            </li>
            <!-- конец пункты меню видны только неавторизованному пользователю -->        
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="">---------</option>
                      <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Сохранить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}

{% block title %}Пароль изменён{% endblock %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
         Пароль изменён
        </div>
        <div class="card-body"> 
          <p>Пароль изменён успешно</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Сброс пароля прошёл успешно</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="../users/login.html">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}